### ISSUE TITLE
Couldn't add font awesome icons in Navbar

### ISSUE THREAD

**Issue by lotfijb** [lotfijb/lotfijb_portfolio#1]
I wanted to add email and twitter icons in navbar but it didn't work.
I would be grateful if you manage to correct it

**Comment by ozair-dev** [comment]
I think I can help you with that.
Where exactly do you want to put the icons.
https://github.com/lotfijb/lotfijb_portfolio/blob/fda9c63d9c3ec285651db642d4b701980fee2cd9/src/Components/Navbar.jsx#L14-L37
